/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import EDD.Graph;
import Views.Sorts.BubbleSort;
import static Objects.Sha256.sha256;
import Objects.User;
import Views.Graph.AdjacencyMatrix;
import Views.Graph.BreadthSearch;
import Views.Graph.DepthSearch;
import Views.Sorts.InsertionSort;
import java.io.File;
import java.io.FileReader;
import java.io.Reader;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Jorge
 */
public class LearningMenu extends javax.swing.JFrame {

    /**
     * Creates new form LearningMenu
     */
    public LearningMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Bubble Sort");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Insertion Sort");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Quick Sort");

        jRadioButton1.setText("Automatico");

        jButton4.setText("Adjacency Matrix");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Breadth Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Depth Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jRadioButton1)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jRadioButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(168, 168, 168))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        FileNameExtensionFilter f = new FileNameExtensionFilter("JSON", "json");
        
        fc.setFileFilter(f);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            int[] arr = null;
            JSONParser parser = new JSONParser();
            try
            {
                
                File fichero = fc.getSelectedFile();
                Reader reader = new FileReader(fichero);
                JSONObject object = (JSONObject) parser.parse(reader);
                JSONArray jsonarr = (JSONArray) object.get("Array");
                arr = new int[jsonarr.size()];
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    
                    arr[i] = ((Long)obj.get("num")).intValue();
                         
                }
                
                this.setVisible(false);
                BubbleSort s = new BubbleSort(arr,false,1);
                this.dispose();
            }
            catch(Exception e)
            {
                System.out.println("JSONArray ERROR!");
            }
            
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        FileNameExtensionFilter f = new FileNameExtensionFilter("JSON", "json");
        
        fc.setFileFilter(f);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            int[] arr = null;
            JSONParser parser = new JSONParser();
            try
            {
                
                File fichero = fc.getSelectedFile();
                Reader reader = new FileReader(fichero);
                JSONObject object = (JSONObject) parser.parse(reader);
                JSONArray jsonarr = (JSONArray) object.get("Array");
                arr = new int[jsonarr.size()];
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    
                    arr[i] = ((Long)obj.get("num")).intValue();
                         
                }
                
                this.setVisible(false);
                InsertionSort s = new InsertionSort(arr,true,1);
                this.dispose();
            }
            catch(Exception e)
            {
                System.out.println("JSONArray ERROR!");
            }
            
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FileNameExtensionFilter f = new FileNameExtensionFilter("JSON", "json");
        
        fc.setFileFilter(f);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            JSONParser parser = new JSONParser();
            try
            {
                
                File fichero = fc.getSelectedFile();
                Reader reader = new FileReader(fichero);
                JSONObject object = (JSONObject) parser.parse(reader);
                JSONArray jsonarr = (JSONArray) object.get("Graph");
                Graph grafo = new Graph(jsonarr.size());
                String[] nodes = new String[jsonarr.size()];
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    
                    nodes[i]=(String)obj.get("Node");
                }
                grafo.addNodes(nodes);
                
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    JSONArray union = (JSONArray) obj.get("Adjacency");
                    String[] uniones = new String[union.size()];
                    
                    for(int j = 0; j<union.size(); j++)
                    {
                        JSONObject node = (JSONObject) union.get(j);
                        uniones[j] = (String)node.get("Node");
                        
                    }
                    grafo.addUniones((String)obj.get("Node"), uniones);
                    
                }
                
                this.setVisible(false);
                AdjacencyMatrix s = new AdjacencyMatrix(grafo.getNodes(),grafo.getMatrix(),true,2);
                this.dispose();
            }
            catch(Exception e)
            {
                System.out.println("JSONArray ERROR!");
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FileNameExtensionFilter f = new FileNameExtensionFilter("JSON", "json");
        
        fc.setFileFilter(f);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            JSONParser parser = new JSONParser();
            try
            {
                
                File fichero = fc.getSelectedFile();
                Reader reader = new FileReader(fichero);
                JSONObject object = (JSONObject) parser.parse(reader);
                JSONArray jsonarr = (JSONArray) object.get("Graph");
                Graph grafo = new Graph(jsonarr.size());
                String[] nodes = new String[jsonarr.size()];
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    
                    nodes[i]=(String)obj.get("Node");
                }
                grafo.addNodes(nodes);
                
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    JSONArray union = (JSONArray) obj.get("Adjacency");
                    String[] uniones = new String[union.size()];
                    
                    for(int j = 0; j<union.size(); j++)
                    {
                        JSONObject node = (JSONObject) union.get(j);
                        uniones[j] = (String)node.get("Node");
                        
                    }
                    grafo.addUniones((String)obj.get("Node"), uniones);
                    
                }
                
                this.setVisible(false);
                BreadthSearch bs = new BreadthSearch(grafo,true,2);
                this.dispose();
            }
            catch(Exception e)
            {
                System.out.println("JSONArray ERROR!");
            }
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        FileNameExtensionFilter f = new FileNameExtensionFilter("JSON", "json");
        
        fc.setFileFilter(f);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            JSONParser parser = new JSONParser();
            try
            {
                
                File fichero = fc.getSelectedFile();
                Reader reader = new FileReader(fichero);
                JSONObject object = (JSONObject) parser.parse(reader);
                JSONArray jsonarr = (JSONArray) object.get("Graph");
                Graph grafo = new Graph(jsonarr.size());
                String[] nodes = new String[jsonarr.size()];
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    
                    nodes[i]=(String)obj.get("Node");
                }
                grafo.addNodes(nodes);
                
                for(int i = 0; i<jsonarr.size(); i++)
                {
                    JSONObject obj = (JSONObject) jsonarr.get(i);
                    JSONArray union = (JSONArray) obj.get("Adjacency");
                    String[] uniones = new String[union.size()];
                    
                    for(int j = 0; j<union.size(); j++)
                    {
                        JSONObject node = (JSONObject) union.get(j);
                        uniones[j] = (String)node.get("Node");
                        
                    }
                    grafo.addUniones((String)obj.get("Node"), uniones);
                    
                }
                
                this.setVisible(false);
                DepthSearch bs = new DepthSearch(grafo,false,2);
                this.dispose();
            }
            catch(Exception e)
            {
                System.out.println("JSONArray ERROR!");
            }
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
